name: Desktop Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]   # add macos-latest, ubuntu-latest later if you want
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - uses: dtolnay/rust-toolchain@stable

      - name: Windows deps (none needed for NSIS)
        if: matrix.platform == 'windows-latest'
        run: echo "NSIS bundles will be produced"

      - run: npm ci
      - run: npm run build

      - name: Build Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: ${{ github.ref_name }}
          releaseDraft: false
          prerelease: false
