name: Desktop Release

on:
  push:
    tags: ['v*.*.*']   # e.g. v0.2.0
  workflow_dispatch:

permissions:
  contents: write       # build job
  # publish job below requests write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix: { os: [windows-latest, macos-13] }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: npm ci
      - run: npm run build

      - name: Build + Publish (Windows MSI / macOS app)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          args: ${{ runner.os == 'Windows' && '--bundles msi --verbose' || '--bundles app --verbose' }}
          tagName: ${{ github.ref_name }}                # v0.1.18
          releaseName: Empress Card Binder ${{ github.ref_name }}
          releaseDraft: false
          prerelease: false
